### ISSUE TITLE
[bug][nagios mode] wrong nagios output format when using conditional steps

### ISSUE THREAD

**Issue by tanguyvda** [alyvix/alyvix#7]
Hello,

I open a new issue for the sake of clarity but it's a bit related to #6 

here is the main script overview:

![image](https://user-images.githubusercontent.com/7352865/82671054-80247600-9c3e-11ea-9d3f-4e1065fbfd8e.png)

here is the nagios output: 

```
OK|open_twitter=0ms;;;; open_centreon_website=2341ms;;;; click_search_icon=2736ms;;;; search_azure=0ms;;;; open_tutorial=445ms;;;; scroll_through_the_tutorial=166ms;;;; open_documentation=0ms;;;; check_documentation_title=557ms;;;; close_chrome=0ms;;;; twitter_fallback=ms;;;;
NOT EXECUTED transactions: twitter_fallback
```

There are two issues there (maybe three)

- While it is a good to be noticed that a script haven't been ran, the fact that it is written after the performance data breaks the whole nagios output format.
- Since the twitter_fallback script hasn't been played its related performance data is broken (twitter_fallback=ms;;;;)

to me, the perfect output should be : 

```
OK, NOT EXECUTED transactions: twitter_fallback|open_twitter=0ms;;;; open_centreon_website=2341ms;;;; click_search_icon=2736ms;;;; search_azure=0ms;;;; open_tutorial=445ms;;;; scroll_through_the_tutorial=166ms;;;; open_documentation=0ms;;;; check_documentation_title=557ms;;;; close_chrome=0ms;;;;
```

note that I've removed the twitter_fallback perfdata, the script hasn't been ran, we can't have 0ms as a value because it is misleading so we just don't put it

my third issue is related to: 
search_azure=0ms;;;;
close_chrome=0ms;;;;
open_documentation=0ms;;;;

search azure is a step where I use the string field of the script to write "azure" in a search field
close_chrome is a step where the mouse moves to the close button of google chrome
open_documentation is a step where I click the link to a documentation

I'm a bit surprised that those steps are executed in 0ms. I've not checked that part of the code so I don't know how it is handled maybe that's normal. 

Regards

**Comment by franzmelchiori** [comment]
Hello tanguyvda,

You can exculde `twitter_fallback` from the output: deselect its `Measure` in the [Alyvix Selector](https://www.alyvix.com/learn/test_case_building/selector_interface_overview.html).

We decided to list the `NOT EXECUTED transactions` on the _third_ line of the nagios output, because it should be legit ([from our understanding](http://nagios-plugins.org/doc/guidelines.html#AEN33)) and it should be intended as a debug information. In fact, you can still know that a test case is broken (in production), because of the subsequent broken transaction with selected `Break` and `Measure` options, `click_search_icon` in your case.

Because of the _0ms_ transactions, you should take into account that Alyvix has a precision of 1ms, but a variable accuracy that depends on the hardware: take a look at the [standard Alyvix CLI output](https://www.alyvix.com/learn/test_case_execution.html#cli-output-format). Moreover, take into account that for every transaction the Alyvix measure is the click-to-appearance time: from the end of the previous interaction to the visual detection of the ongoing transaction.

Thanks for cooperating,
Francesco
